### ISSUE TITLE
Some audio updates

### ISSUE THREAD

**Issue by aviraxp** [AOSPA/android_device_oneplus_oneplus2#2]
How about cherry-picking these commits from CM?

https://github.com/CyanogenMod/android_device_oneplus_oneplus2/commit/6db937c05b16942c30faca4fcc1cf5eaf371dbc7
https://github.com/CyanogenMod/android_device_oneplus_oneplus2/commit/d35efbed5b1dae17ea8ca0b003ffd3e5d831c8d3

I noticed that we have already changed some audio config, but it seems that further changes are needed, because these broken audio features will cause random stop when playing music (prboably because of the really small buffer) and other wired issues.

**Comment by evan-a-a** [comment]
Please submit to our gerrit @ https://gerrit.aospa.co
